name = "ModalFLewToFirstOrder"
uuid = "9d09a47b-cb48-451c-804c-767122fdad8d"
authors = ["Alberto Paparella <pprlrt@unife.it>"]
version = "0.1.0"

[deps]
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
SoleLogics = "0.13.0"
UUIDs = "1.9.3 - 1.11.0"
